version: "3.9"

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: rem-waste-api
    ports:
      - "3001:3001"
    restart: unless-stopped

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    container_name: rem-waste-ui
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped

  automation:
    build:
      context: ./automation
      dockerfile: Dockerfile
    container_name: rem-waste-automation
    depends_on:
      - ui
      - api
    profiles:
      - test